%% [] = writeSpatialGraphLine(pt1,pt2,outputFilename,neuriteID,EdgePtRadius)
% Write a line as a SpatialGraphTree for Amira
% Line is defined by two points
% Input:
% - pt1: starting point of line (1x3)
% - pt2: ending point of line (1x3)
% - outputFilename
% - neuriteID: (optional; default: 24, C2 Column)
% - EdgePtRadius: (optional; default: 0)
function [] = writeSpatialGraphLine(pt1,pt2,outputFilename,neuriteID,EdgePtRadius)

    if length(pt1)~=length(pt2) || length(pt1)~=3
       error(['pt1 and pt2 both need to be a vector 1x3']); 
    end

    if (strcmp(outputFilename(end-2:end), '.am'))
        fname = outputFilename;  
    else
        fname = [outputFilename '.am'];
    end
    
    numVertex = 4;
    numEdges = 1;
    numPoints = 2;
    
    if nargin < 4
        neuriteID = 24; % C2 column
    end
    if nargin < 5
        EdgePtRadius = 0;
    end
    
    %% Header Information 
    strHeader = sprintf(['# AmiraMesh 3D ASCII 2.0\n\n\n' ...
                    'define VERTEX %d\n' ...
                    'define EDGE %d\n' ...
                    'define POINT %d\n\n' ...                       
                    'Parameters {\n' ...
                    '    GraphLabels {\n' ...
                    '        Neuron {\n' ...
                    '            Dendrite {\n' ...
                    '                ApicalDendrite {\n' ...
                    '                    Color 1 0.5 0.5,\n' ...
                    '                    Id 4\n' ...
                    '                }\n' ...
                    '                BasalDendrite {\n' ...
                    '                    Color 0.8 0.4 0.4,\n' ...
                    '                    Id 5\n' ...
                    '                }\n' ...
                    '                Color 1 0 0,\n' ...
                    '                Id 3\n' ...
                    '            }\n' ...
                    '            Axon {\n' ...
                    '                Color 0 0 1,\n' ...
                    '                Id 6\n' ...
                    '            }\n' ...
                    '            Soma {\n' ...
                    '                Color 1 0 0,\n' ...
                    '                Id 7\n' ...
                    '            }\n' ...
                    '            Color 1 0 0,\n' ...
                    '            Id 2\n' ...
                    '        }\n' ...
                    '        Landmark {\n' ...
                    '            Pia {\n' ...
                    '                Color 0 1 0.5,\n' ...
                    '                Id 9\n' ...
                    '            }\n' ...
                    '            Vessel {\n' ...
                    '                Color 1 0.5 0,\n' ...
                    '                Id 10\n' ...
                    '            }\n' ...
                    '            Barrel {\n' ...
                    '                aRow {\n' ...
                    '                    A1 {\n' ...
                    '                        Color 1 0.2 0.2,\n' ...
                    '                        Id 13\n' ...
                    '                    }\n' ...
                    '                    A2 {\n' ...
                    '                        Color 1 0.2 0.2,\n' ...
                    '                        Id 14\n' ...
                    '                    }\n' ...
                    '                    A3 {\n' ...
                    '                        Color 1 0.2 0.2,\n' ...
                    '                        Id 15\n' ...
                    '                    }\n' ...
                    '                    A4 {\n' ...
                    '                        Color 1 0.2 0.2,\n' ...
                    '                        Id 16\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.2 0.2,\n' ...
                    '                    Id 12\n' ...
                    '                }\n' ...
                    '                bRow {\n' ...
                    '                    B1 {\n' ...
                    '                        Color 1 0.25 0.25,\n' ...
                    '                        Id 18\n' ...
                    '                    }\n' ...
                    '                    B2 {\n' ...
                    '                        Color 1 0.25 0.25,\n' ...
                    '                        Id 19\n' ...
                    '                    }\n' ...
                    '                    B3 {\n' ...
                    '                        Color 1 0.25 0.25,\n' ...
                    '                        Id 20\n' ...
                    '                    }\n' ...
                    '                    B4 {\n' ...
                    '                        Color 1 0.25 0.25,\n' ...
                    '                        Id 21\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.25 0.25,\n' ...
                    '                    Id 17\n' ...
                    '                }\n' ...
                    '                cRow {\n' ...
                    '                    C1 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 23\n' ...
                    '                    }\n' ...
                    '                    C2 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 24\n' ...
                    '                    }\n' ...
                    '                    C3 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 25\n' ...
                    '                    }\n' ...
                    '                    C4 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 26\n' ...
                    '                    }\n' ...
                    '                    C5 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 27\n' ...
                    '                    }\n' ...
                    '                    C6 {\n' ...
                    '                        Color 1 0.3 0.3,\n' ...
                    '                        Id 28\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.3 0.3,\n' ...
                    '                    Id 22\n' ...
                    '                }\n' ...
                    '                dRow {\n' ...
                    '                    D1 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 30\n' ...
                    '                    }\n' ...
                    '                    D2 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 31\n' ...
                    '                    }\n' ...
                    '                    D3 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 32\n' ...
                    '                    }\n' ...
                    '                    D4 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 33\n' ...
                    '                    }\n' ...
                    '                    D5 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 34\n' ...
                    '                    }\n' ...
                    '                    D6 {\n' ...
                    '                        Color 1 0.35 0.35,\n' ...
                    '                        Id 35\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.35 0.35,\n' ...
                    '                    Id 29\n' ...
                    '                }\n' ...
                    '                eRow {\n' ...
                    '                    E1 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 37\n' ...
                    '                    }\n' ...
                    '                    E2 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 38\n' ...
                    '                    }\n' ...
                    '                    E3 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 39\n' ...
                    '                    }\n' ...
                    '                    E4 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 40\n' ...
                    '                    }\n' ...
                    '                    E5 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 41\n' ...
                    '                    }\n' ...
                    '                    E6 {\n' ...
                    '                        Color 1 0.4 0.4,\n' ...
                    '                        Id 42\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.4 0.4,\n' ...
                    '                    Id 36\n' ...
                    '                }\n' ...
                    '                greekRow {\n' ...
                    '                    Alpha {\n' ...
                    '                        Color 1 0.1 0.1,\n' ...
                    '                        Id 44\n' ...
                    '                    }\n' ...
                    '                    Beta {\n' ...
                    '                        Color 1 0.1 0.1,\n' ...
                    '                        Id 45\n' ...
                    '                    }\n' ...
                    '                    Gamma {\n' ...
                    '                        Color 1 0.1 0.1,\n' ...
                    '                        Id 46\n' ...
                    '                    }\n' ...
                    '                    Delta {\n' ...
                    '                        Color 1 0.1 0.1,\n' ...
                    '                        Id 47\n' ...
                    '                    }\n' ...
                    '                    Color 1 0.1 0.1,\n' ...
                    '                    Id 43\n' ...
                    '                }\n' ...
                    '                Color 0 1 0,\n' ...
                    '                Id 11\n' ...
                    '            }\n' ...
                    '            Color 0 1 1,\n' ...
                    '            Id 8\n' ...
                    '        }\n' ...
                    '        Id 0,\n' ...
                    '        Color 0 0 0\n' ...
                    '    }\n' ...
                    '    ContentType "HxSpatialGraph"\n' ...
                    '}\n\n' ...  
                    'VERTEX { float[3] VertexCoordinates } @1\n' ...
                    'VERTEX { int GraphLabels } @2\n' ...
                    'EDGE { int[2] EdgeConnectivity } @3\n' ...
                    'EDGE { int NumEdgePoints } @4\n' ...
                    'EDGE { int GraphLabels } @5\n' ...
                    'POINT { float[3] EdgePointCoordinates } @6\n' ...
                    'POINT { float Radius } @7\n\n' ...
                    '# Data section follows'], ... 
                numVertex,numEdges,numPoints);
            
        %% Write to file
        fid = fopen(fname,'w');
        
        if fid ~= -1
            fprintf(fid,'%s\n',strHeader);
            
            % (1) Vertex Coordinates
            fprintf(fid,'%s\n','@1');
            fprintf(fid,'%e %e %e\n',pt1(1),pt1(2),pt1(3));           
            fprintf(fid,'%e %e %e\n',pt1(1),pt1(2),pt1(3));           
            fprintf(fid,'%e %e %e\n',pt2(1),pt2(2),pt2(3));           
            fprintf(fid,'%e %e %e\n',pt2(1),pt2(2),pt2(3));           
            fprintf(fid,'%s\n','');

            % (2) Vertex GraphLabels
            fprintf(fid,'%s\n','@2');
            for i = 1:numVertex
                fprintf(fid,'%d\n',neuriteID);
            end
            fprintf(fid,'%s\n','');

            % (3) Edge Connectivity
            fprintf(fid,'%s\n','@3');
            fprintf(fid,'0 2\n');
            fprintf(fid,'%s\n','');
            
            % (4) NumEdgePoints
            fprintf(fid,'%s\n','@4');
            fprintf(fid,'%d\n',numPoints);
            fprintf(fid,'%s\n','');

            % (5) Edge GraphLabels
            fprintf(fid,'%s\n','@5');
            fprintf(fid,'%d\n',neuriteID);
            fprintf(fid,'%s\n','');
            
            % (6) Edge Coordinates
            fprintf(fid,'%s\n','@6');
            fprintf(fid,'%e %e %e\n',pt1(1),pt1(2),pt1(3));
            fprintf(fid,'%e %e %e\n',pt2(1),pt2(2),pt2(3));
            fprintf(fid,'%s\n','');
            
            % (7) Edge Points Radius            
            fprintf(fid,'%s\n','@7');
            for i = 1:numPoints
                fprintf(fid,'%f\n',EdgePtRadius);
            end
            fprintf(fid,'%s\n','');
            
            % Close file
            fclose(fid);
        else
            error(['Failed writing ' fname ' to the disk!']); 
        end

end